Misra C Compliances for files
LoMesh-ORG/LWmesh pull request #75
Opened 2021-01-15 16:29 UTC by NidhiSura

Misra C compliances implemented for following files:
1. EEPROM.c
2. circularbuffer.c
3. crc.c
4. led.c
5. uart_default_cotrol.c

2021-01-16 03:28 UTC, sramrajkar commented on app/app_inc/crc.h
> +    uint16_t crc16_app(uint8_t* dptr, uint16_t len, uint16_t seed);
What was the reported MISRA error here?

2021-01-16 15:54 UTC, sramrajkar commented on app/app_src/circular_buffer.c
> +    int sizeint = (int)size;
What was the error here? Also we should use unsigned int when signed arithmetic is not needed

2021-01-16 15:55 UTC, sramrajkar commented on app/app_src/circular_buffer.c
> +    int sizeint2 = (int)size;
Use unsigned if signed arithmetic is not needed

2021-01-16 15:56 UTC, sramrajkar commented on app/app_src/circular_buffer.c
> +//    return -1;
delete if not needed

2021-01-16 15:57 UTC, sramrajkar commented on app/app_src/crc.c
> +    //uint8_t* ptr = (uint8_t*)dptr;
delete this if not needed

2021-01-16 16:03 UTC, sramrajkar commented on app/app_src/crc.c
> +        while(fullbool){} //Wait if the module is busy
This is bug. Code will lock up here. same at line 54.
The original code is checking for hardware register flags we can replace this.

2021-01-16 16:04 UTC, sramrajkar commented on app/app_src/led.c
> +{   int retvar1;
create variable on new line

2021-01-16 16:05 UTC, sramrajkar commented on app/app_src/crc.c
> +    bool fullbool;
create all variables at the start of the function. Just a style issue.

2021-01-16 16:05 UTC, sramrajkar commented on app/app_src/led.c
> +    for(int i = 0; i < 2; i++)
use unsigned int. What was the error here?

2021-01-16 16:07 UTC, sramrajkar commented on app/app_src/uart_default_control.c
> +            }
Not needed. was this for condition statement? Lets talk over a call and see what we can do to solve this issue

2021-01-16 16:08 UTC, sramrajkar commented on app/app_src/uart_default_control.c
> +                int setbaud2 = set_uart_baud(DATAEE_ReadByte_Platform(UARTBaud));
Do we need to have return values captured?

2021-01-16 16:08 UTC, sramrajkar commented on app/app_src/uart_default_control.c
> +                uint8_t uart_baud_status = (uint8_t)set_uart_baud(current_baud_rate);
Do we need to capture the returned values?

2021-01-16 16:09 UTC, sramrajkar requested changes
Some bugs are present

2021-01-18 06:59 UTC, NidhiSura commented on app/app_inc/crc.h
> +    uint16_t crc16_app(uint8_t* dptr, uint16_t len, uint16_t seed);
crc.c:17:20: [misra-c2012-11.5] A conversion should not be performed from pointer to void into pointer to object

2021-01-18 07:02 UTC, NidhiSura commented on app/app_src/circular_buffer.c
> +    int sizeint = (int)size;
circularbuffer.c:64:26: [misra-c2012-10.4] Both operands of an operator in which the usual arithmetic conversions are performed shall have the same essential type category

Yeah, I'll change it to an unsigned int.

2021-01-19 06:20 UTC, atharva-18 commented on app/app_src/uart_default_control.c
> +                int setbaud2 = set_uart_baud(DATAEE_ReadByte_Platform(UARTBaud));
Yes, according to misra-c2012-17.7, the value returned by a non-void function must be used.

2021-01-19 06:20 UTC, atharva-18 commented on app/app_src/uart_default_control.c
> +                uint8_t uart_baud_status = (uint8_t)set_uart_baud(current_baud_rate);
Yes, according to misra-c2012-17.7, the value returned by a non-void function must be used.

2021-01-25 16:36 UTC, atharva-18 commented
@sramrajkar Please check the recent commits.

2021-01-26 01:53 UTC, sramrajkar commented on app/app_src/EEPROM.c
> +    if(eeprom_write_flags.flag_master > 0){
Check for (0 != eeprom_write_flags.flag_master)

2021-01-26 01:53 UTC, sramrajkar commented on app/app_src/EEPROM.c
> +        else if(eeprom_write_flags.flag_appkey > 0){
Same as above

2021-01-26 01:54 UTC, sramrajkar commented on app/app_src/circular_buffer.c
> +    ctx->max_size = sizeint - 1u;
What is the error here?

2021-01-26 01:55 UTC, sramrajkar commented on app/app_src/circular_buffer.c
> +        }
Indentation

2021-01-26 01:56 UTC, sramrajkar commented on app/app_src/circular_buffer.c
> +    if ((sizeint2 == 0u) || (size <= num)) {
Flip constant and variable so that the comparision is 0u == sizeint2

2021-01-26 01:57 UTC, sramrajkar commented on app/app_src/crc.c
> +        while(CRCCON0bits.FULL == 1){} //Wait if the module is busy
flip constant and hardware bit

2021-01-26 01:57 UTC, sramrajkar commented on app/app_src/crc.c
> +    while(CRCCON0bits.BUSY == 1){} //Wait if the module is busy
same as above

2021-01-26 01:58 UTC, sramrajkar commented on app/app_src/led.c
> +    uint8_t ledEventStatus = queueLedEvent(0,2000);
Lets talk about this on the call

2021-01-26 01:58 UTC, sramrajkar commented on app/app_src/led.c
> +            if(0 == Eduration){
whats the error here?

2021-01-26 01:59 UTC, sramrajkar commented on app/app_src/led.c
> +                set_timer0base(&ledtimer, temp.eventDuration);
let talk about this

2021-01-26 01:59 UTC, sramrajkar commented on app/app_src/uart_default_control.c
> +            }
lets talk about this

2021-01-26 01:59 UTC, sramrajkar commented on app/app_src/uart_default_control.c
> +            if(BLEN_GetValue() && true){
Lets talk about this

2021-01-26 02:00 UTC, sramrajkar commented on app/app_src/uart_default_control.c
> +                uint8_t uart_baud_status = (uint8_t)set_uart_baud(current_baud_rate);
Lets talk about this

2021-01-26 03:50 UTC, sramrajkar commented on app/app_src/led.c
> +    uint8_t ledEventStatus = queueLedEvent(0,2000);
(void) queueLedEvent(0,2000);

2021-01-26 03:54 UTC, sramrajkar commented on app/app_src/crc.c
> +    bool fullbool;
unused variable

2021-01-26 04:00 UTC, sramrajkar commented on app/app_src/uart_default_control.c
> +            if(BLEN_GetValue() && true){
0 != BLEN_GetValue()

2021-01-27 08:22 UTC, atharva-18 commented
@sramrajkar I have addressed the remaining issues.

2021-02-16 17:27 UTC, closed without merging